maintenance: Align bitrise emulator

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -53,11 +53,6 @@ workflows:
           inputs:
             - gradlew_path: "$PROJECT_LOCATION/gradlew"
           is_always_run: true
-      # - android-build-for-ui-testing@0.1.7:
-      #     inputs:
-      #       - module: "$MODULE"
-      #       - arguments: "--no-build-cache"
-      #       - variant: "$VARIANT"
       - gradle-runner@2:
           inputs:
             - gradlew_path: "$PROJECT_LOCATION/gradlew"
@@ -65,7 +60,7 @@ workflows:
             - gradle_task: "$MODULE:assembleDebug"
       - git::https://github.com/stepstone-tech/steps-avd-manager.git@core:
           inputs:
-            - version: "33"
+            - version: "28"
             - verbose_mode: "true"
             - custom_hw_config: |-
                 disk.dataPartition.size=1024M
@@ -86,38 +81,30 @@ workflows:
                 vm.heapSize=256
             - custom_command_flags: "-no-window -no-audio -debug-init -no-boot-anim -no-snapshot"
             - boot_wait_time: "300"
+            - profile: pixel
             - emulator_channel: "0"
           title: Create & start emulator
       - wait-for-android-emulator@1: {}
-      - script@1.1.5:
+      - script@1.2:
           timeout: 3000
           inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                # fail if any commands fails
-                # set -e
-                # debug log
-                set -x
-                echo "Disabling animations"
-                adb shell settings put global window_animation_scale 0
-                adb shell settings put global transition_animation_scale 0
-                adb shell settings put global animator_duration_scale 0
-                echo "Saving logcat logs to file"
-                ( adb logcat -v threadtime & echo $! >&3 ) 3>app/build/logcat.pid | tee app/build/adb_logcat.log 2>&1 > /dev/null
-                echo "Starting Android tests!"
-                local gradleExitStatus="0"
-                ./gradlew ${MODULE}:debugExecuteScreenshots --info --stacktrace --no-build-cache 
-                gradleExitStatus=${PIPESTATUS[0]}
-                kill -9 $(cat app/build/logcat.pid) | true
-                if [[ ${gradleExitStatus} -gt 0 ]]; then
-                  echo "Build failed for some reason, please check the logs."
-                  exit 1
-                fi
+            - content:
+                "#!/usr/bin/env bash\n# fail if any commands fails\n# set -e\n#
+                debug log\nset -x\necho \"Disabling animations\"\nadb shell settings put
+                global window_animation_scale 0\nadb shell settings put global transition_animation_scale
+                0\nadb shell settings put global animator_duration_scale 0\necho \"Saving
+                logcat logs to file\"\n( adb logcat -v threadtime & echo $! >&3 ) 3>app/build/logcat.pid
+                | tee app/build/adb_logcat.log 2>&1 > /dev/null\necho \"Starting Android
+                tests!\"\nlocal gradleExitStatus=\"0\"\n./gradlew ${UI_TEST_TARGET} --info
+                --stacktrace --no-build-cache \ngradleExitStatus=${PIPESTATUS[0]}\nkill
+                -9 $(cat app/build/logcat.pid) | true\nif [[ ${gradleExitStatus} -gt 0
+                ]]; then\n  echo \"Build failed for some reason, please check the logs.\"\n
+                \ exit 1\nfi"
           title: Run UI tests
       - custom-test-results-export@1.0:
           inputs:
             - search_pattern: "*.xml"
-            - base_path: "$BITRISE_SOURCE_DIR/app/build/outputs/androidTest-results"
+            - base_path: "$BITRISE_SOURCE_DIR/$MODULE/build/outputs/androidTest-results"
             - test_name: Emulator tests
       - deploy-to-bitrise-io@2: {}
       - save-gradle-cache@1: {}
@@ -133,10 +120,10 @@ app:
       PROJECT_LOCATION: "."
     - opts:
         is_expand: false
-      MODULE: mobile-design
+      MODULE: ":mobile-design"
     - opts:
         is_expand: false
-      VARIANT: ""
+      VARIANT: debug
     - opts:
         is_expand: false
       UI_TEST_TARGET: ":mobile-design:debugExecuteScreenshotTests"
